### ISSUE TITLE
npm test is failing

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-app#144]
In CI and locally, since I upgraded to Electron 19.

Errors locally:

```
 % npm test

> datasette-app@0.2.1 test
> mocha



  Application launch
    1) "before each" hook for "shows an initial window"


  0 passing (3s)
  1 failing

  1) Application launch
       "before each" hook for "shows an initial window":
     Error: Failed to create session.
unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /Users/simon/Dropbox/Development/datasette-app/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
      at Object.startWebDriverSession (node_modules/webdriver/build/utils.js:34:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Function.newSession (node_modules/webdriver/build/index.js:35:45)
      at async exports.remote (node_modules/webdriverio/build/index.js:53:22)
```

**Comment by simonw** [comment]
Maybe I should switch these tests to Playwright, as seen here:
- #133

**Comment by simonw** [comment]
Fixed this in:
- #133
