### ISSUE TITLE
On first launch loading page doesn't switch to homepage after server starts

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-app#65]
It just sits there spinning, even though `ps aux | grep xyz` confirms that the server has started.

Also, the application menu sticks as the Electron default rather than showing the Datasette app menu.

Hmm... just noticed this:
```
.datasette-app % ps aux | grep xyz
simon            14445   0.2  0.1  4985064  44452   ??  S     5:40PM   0:00.88 /Users/simon/.datasette-app/venv/bin/python3.9 /Users/simon/.datasette-app/venv/bin/datasette --port 8003 --version-note xyz-for-datasette-app --setting sql_time_limit_ms 10000 --setting max_returned_rows 2000 --setting facet_time_limit_ms 1000 --setting max_csv_mb 0
simon            13134   0.2  0.1  5256424  44752   ??  S     4:56PM   0:05.82 /Users/simon/.datasette-app/venv/bin/python3.9 /Users/simon/.datasette-app/venv/bin/datasette --port 8002 --version-note xyz-for-datasette-app --setting sql_time_limit_ms 10000 --setting max_returned_rows 2000 --setting facet_time_limit_ms 1000 --setting max_csv_mb 0
```
So it looks like the server was started twice, once on port 8002 and once on port 8003.

**Comment by simonw** [comment]
If I quit and then relaunch the application it works fine.

**Comment by simonw** [comment]
Here's the cause of the bug:
```
(node:14668) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
    at DatasetteServer.openPath (/Users/simon/Dropbox/Development/datasette-app/main.js:224:39)
    at initializeApp (/Users/simon/Dropbox/Development/datasette-app/main.js:308:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/simon/Dropbox/Development/datasette-app/main.js:717:3
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:14668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by simonw** [comment]
Code in question: https://github.com/simonw/datasette-app/blob/7b075efd92252f082b5c24bafc13e8e0b9ddf952/main.js#L304-L310

https://github.com/simonw/datasette-app/blob/7b075efd92252f082b5c24bafc13e8e0b9ddf952/main.js#L217-L228

**Comment by simonw** [comment]
That's why: it's a focus problem. If `opts.forceMainWindow` is true AND there is only one wisible window, it attempts to grab the single existing focused window and load things there.

It should use the first item in `BrowserWindow.getAllWindows()` instead.
