### ISSUE TITLE
Importing a large CSV file fails with a javascript error pop-up (possible timeout issue)

### ISSUE THREAD

**Issue by ageitgey** [simonw/datasette-app#84]
System: Macbook Pro (M1) / Big Sur 11.4

Steps followed:

1. Downloaded Datasette.app from website (Mac version). 
2. Launched app (from ~/Downloads). It seemed to be functioning correctly.
3. Used menu at top to "Open CSV.." and chose [this 150MB csv file](https://mcorgstatic.blob.core.windows.net/cms-price/Red%20Wing.csv) with 789968 lines of data. Note that the file starts with a unicode U+FEFF character.

Result: Error popup with this error

```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
at DatasetteServer.openPath (/private/var/folders/nn/t5x7tzq140b0g7qldcxgcnrm0000gn/T/AppTranslocation/A314CF18-67D2-4D08-BFD9-41B0A91BDF54/d/Datasette.app/Contents/Resources/app.asar/main.js:220:49)
at Timeout._onTimeout (/private/var/folders/nn/t5x7tzq140b0g7qldcxgcnrm0000gn/T/AppTranslocation/A314CF18-67D2-4D08-BFD9-41B0A91BDF54/d/Datasette.app/Contents/Resources/app.asar/main.js:545:25)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
```

<img width="301" alt="Screen Shot 2021-09-09 at 9 33 38 AM" src="https://user-images.githubusercontent.com/896692/132653095-e663ef4a-32ff-468a-bd48-6e79add12c3b.png">

I saw #68, but this seemed like a different result in a similar case.

**Comment by ageitgey** [comment]
Update: I think this issue is actually probably due to initially running Datasette.app from inside the `~/Downloads` folder as explained in https://github.com/simonw/datasette-app/issues/66#issuecomment-915903803. I think the app is running with a broken Python install for the reasons explained there.

After deleting my venv and re-running Datasette.app from /Applications/, this error went away. So I think if you fix https://github.com/simonw/datasette-app/issues/66#issuecomment-915903803, this error is no longer relevant and can be ignored.
